### ISSUE TITLE
Don't build pull requests in CircleCI

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#195]
The CircleCI config is currently building deployment bundles for pull requests, e.g. [235](https://circleci.com/gh/mozilla/fxa-email-service/235). We need to add a filter to ignore all branches so that it only builds for tags.

For instance, [this config](https://github.com/mozilla/fxa-email-event-proxy/blob/master/.circleci/config.yml) works how we want in [fxa-email-event-proxy](https://github.com/mozilla/fxa-email-event-proxy):

```yaml
workflows:
  version: 2

  build-test-push:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/

            tags:
              only: /^v[0-9.]+$/
```
